Repository tiangolo/nginx-rtmp-docker, pull requests merged in 2024-03, with the labels that each got.

#65 ✨ Add support for multiarch builds, including ARM (e.g. Mac M1)
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  scripts/build-push.sh
  scripts/build.sh
  scripts/docker-login.sh
Labels: feature

#66 👷 Fix multiarch deploy build
  .github/workflows/deploy.yml
Labels: bug

#70 🔧 Update `latest-changes.yml`
  .github/workflows/latest-changes.yml
Labels: internal

#72 🔧 Add GitHub templates for discussions and issues, and security policy
  .github/DISCUSSION_TEMPLATE/questions.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/privileged.yml
  SECURITY.md
Labels: internal
